sesion_07/movies/urls.py
"""Movies app URLs"""

from django.urls import path

from movies import views

app_name = "movies"
urlpatterns = [
    path("", views.list_movies, name="list"),
    path("<int:pk>", views.MovieDetailView.as_view(), name="retrieve"),
    path("director/create", views.create_director_with_normal_form, name="create_director"),
]

sesion_07/reviews/urls.py
"""URL config for reviews"""

from django.urls import path

from . import views

app_name = "reviews"
urlpatterns = [
    path("", views.list_reviews, name="list"),
    path("new-review/<int:pk>", views.review_movie, name="create"),
]

sesion_07/users/urls.py
"""Users app URL config"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sesion_07/movies/models.py
"""Movies app models"""

from django.db import models

from reviews.models import Review


class Movie(models.Model):
    """Movie model for movies app"""
    name = models.CharField(max_length=255)
    director = models.ForeignKey("Director", on_delete=models.CASCADE)
    release_date = models.DateField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def has_user_review(self, user):
        return Review.objects.filter(movie=self, user=user).exists()


class Director(models.Model):
    """Director of a movie"""
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birthday = models.DateField(blank=True, null=True)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name

sesion_07/movies/forms.py
"""Forms from movies app"""

from datetime import date

from django import forms

from .models import Director

class DirectorForm(forms.ModelForm):
    class Meta:
        model = Director
        fields = '__all__'

    def clean_birthday(self):
        birthday = self.cleaned_data.get("birthday")

        if birthday > date.today():
            raise forms.ValidationError("El cumpleaños está en el futuro")

        return birthday

    def clean(self):
        first_name = self.cleaned_data.get("first_name")
        last_name = self.cleaned_data.get("last_name")

        director_exists = Director.objects.filter(
            first_name=first_name,
            last_name=last_name
        ).exists()

        if director_exists:
            raise forms.ValidationError("El director ya existe")

        return self.cleaned_data

sesion_07/movies/views.py
"""Movies views"""

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic as generic_views

from .forms import DirectorForm
from .models import Movie

# Class-based views


class MovieDetailView(LoginRequiredMixin, generic_views.DetailView):
    model = Movie


# Function-based views

@login_required
def list_movies(request):
    movies = Movie.objects.all()

    for movie in movies:
        movie.reviewed = movie.has_user_review(request.user)

    context = {"movies": movies}
    return render(request, "movies/list.html", context)


@login_required
def create_director_with_normal_form(request):
    form = DirectorForm()
    if request.method == 'POST':
        form = DirectorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:list")
    return render(request, "movies/create_director.html", {"form": form})

sesion_07/templates/movies/create_director.html
{% extends '_base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">
     Crear director
    </h1>

    {% for error in form.non_field_errors %}
    <div class="notification is-danger is-light">
      {{ error }}
    </div>
    {% endfor %}

    <form method="post">
      {% csrf_token %}

      <div class="field">
        <label for="id_first_name" class="label">Nombre(s):</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="first_name"
            {% if form.errors %}value="{{ form.first_name.value }}"{% endif %}
            id="id_first_name"
            required
          />
        </div>
      </div>

      <div class="field">
        <label for="id_last_name" class="label">Apellido(s):</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="last_name"
            {% if form.errors %}value="{{ form.last_name.value }}"{% endif %}
            id="id_last_name"
            required
          />
        </div>
      </div>    
      
      <div class="field">
        <label for="id_birthday" class="label">Cumpleaños:</label>
        <div class="control">
          <input
            class="input{% if form.birthday.errors %} is-danger{% endif %}"
            type="date"
            name="birthday"
            id="id_birthday"
            {% if form.errors %}value="{{ form.birthday.value }}"{% endif %}
            required
          />
        </div>
        {% for error in form.birthday.errors %}
        <p class="help is-danger">{{ error }}</p>
        {% endfor %}
      </div>

      <button class="button is-link" type="submit">
        Crear
      </button>

    </form>
</section>
{% endblock content %}

sesion_07/templates/movies/list.html
{% extends '_base.html' %}

{% block content %}
{% include '_navbar.html' %}
<section class="section">
  <div class="container">
    <h1 class="title">
      Lista de películas
    </h1>

    <div class="content">
      <ul>
        {% for movie in movies %}
        <li>
          {{ movie.name }} de {{ movie.director.full_name }}
          <br>
          <a href="{% url 'movies:retrieve' movie.pk %}">Detalle</a>
          {% if not movie.reviewed %}
          |
          <a href="{% url 'reviews:create' movie.pk %}">Reseñar</a> 
          {% endif %}
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</section>
{% endblock content %}

sesion_07/templates/movies/movie_detail.html
{% extends '_base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">
      Detalle de película
    </h1>

    <div class="content">
      <h2 class="has-text-link">{{ movie.name }}</h2>
      <h4>Fecha de salida</h4>
      <p>{{ movie.release_date }}</p>
      <h4>Detalles de director</h4>
      <ul>
        <li>Nombre(s): {{ movie.director.first_name }}</li>
        <li>Apellido(s): {{ movie.director.last_name }}</li>
        <li>Cumpleaños: {{ movie.director.birthday }}</li>
      </ul>
    </div>
  </div>
</section>
{% endblock content %}