sesion_07/reviews/urls.py
"""URL config for reviews"""

from django.urls import path

from . import views

app_name = "reviews"
urlpatterns = [
    path("", views.list_reviews, name="list"),
    path("new-review/<int:pk>", views.review_movie, name="create"),
]

sesion_07/users/urls.py
"""Users app URL config"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sesion_07/templates/_base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
    />
    {% block meta %}{% endblock meta %}
    {% block title %}
    <title>Rotten Tomatoes</title>
    {% endblock title %}
  </head>
  <body>
    {% block content %}{% endblock content %}
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

sesion_07/templates/_navbar.html
{% load static %}

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="{% url 'reviews:list' %}">
      <img
        src="{% static 'img/logo.png' %}"
        height="28"
      />
    </a>

    <a
      role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbarBasicExample"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item"> Inicio </a>

      <a class="navbar-item"> Películas </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link"> Más </a>

        <div class="navbar-dropdown">
          <a class="navbar-item"> About </a>
          <a class="navbar-item"> Jobs </a>
          <a class="navbar-item"> Contact </a>
          <hr class="navbar-divider" />
          <a class="navbar-item"> Report an issue </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a href="{% url 'users:logout' %}" class="button is-danger"> Cerrar sesión </a>
        </div>
      </div>
    </div>
  </div>
</nav>