sesion_07/users/urls.py
"""Users app URL config"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sesion_07/users/models.py
"""Models for users"""

from django.db import models


from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    birthday = models.DateField(blank=True, null=True)

sesion_07/users/forms.py
"""Users forms"""

from django import forms

from users.models import User


class SignupForm(forms.Form):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    password = forms.CharField(required=True)
    password_confirmation = forms.CharField(required=True)

    def clean_username(self):
        username = self.cleaned_data.get('username')

        user_exists = User.objects.filter(username=username).exists()
        if user_exists:
            raise forms.ValidationError("El usuario ya existe")

        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')

        email_exists = User.objects.filter(email=email).exists()
        if email_exists:
            raise forms.ValidationError("El correo ya está en uso")

        return email

    def clean(self):
        password = self.cleaned_data.get('password')
        password_confirmation = self.cleaned_data.get('password_confirmation')

        if password != password_confirmation:
            raise forms.ValidationError("Las contraseñas no coinciden")

    def save(self):
        data = self.cleaned_data
        data.pop('password_confirmation')
        return User.objects.create_user(**data)

sesion_07/users/views.py
"""Users app views"""

from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views import generic as generic_views

from .forms import SignupForm


class LoginView(auth_views.LoginView):
    template_name = "users/login.html"


class SignupView(generic_views.FormView):
    template_name = "users/signup.html"
    form_class = SignupForm
    success_url = reverse_lazy("reviews:list")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return super().form_valid(form)

sesion_07/templates/users/login.html
{% extends '_base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Iniciar sesión</h1>

    {% for error in form.non_field_errors %}
    <div class="notification is-danger is-light">
      {{ error }}
    </div>
    {% endfor %}

    <form action="{% url 'users:login' %}" method="post">
      {% csrf_token %}

      <div class="field">
        <label for="username-id" class="label">Usuario:</label>
        <div class="control">
          <input class="input" type="text" name="username" id="username-id" required />
        </div>
      </div>

      <div class="field">
        <label for="password-id" class="label">Contraseña:</label>
        <div class="control">
          <input class="input" type="password" name="password" id="password-id" required />
        </div>
      </div>

      <button class="button is-link" type="submit">Ingresar</button>
    </form>
  </div>
</section>
{% endblock content %}

sesion_07/templates/users/signup.html
{% extends '_base.html' %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Crear usuario</h1>

    {% for error in form.non_field_errors %}
    <div class="notification is-danger is-light">
      {{ error }}
    </div>
    {% endfor %}

    <form method="post">
      {% csrf_token %}

      <div class="field">
        <label for="username-id" class="label">Usuario:</label>
        <div class="control">
          <input
            class="input{% if form.username.errors %} is-danger{% endif %}"
            type="text"
            name="username"
            id="username-id"
            {% if form.errors %}value="{{ form.username.value }}"{% endif %}
            required
          />
        </div>
        {% for error in form.username.errors %}
        <p class="help is-danger">{{ error }}</p>
        {% endfor %}
      </div>

      <div class="field">
        <label for="email-id" class="label">Correo electrónico:</label>
        <div class="control">
          <input
            class="input{% if form.email.errors %} is-danger{% endif %}"
            type="email"
            name="email"
            id="email-id"
            {% if form.errors %}value="{{ form.email.value }}"{% endif %}
            required
          />
        </div>
        {% for error in form.email.errors %}
        <p class="help is-danger">{{ error }}</p>
        {% endfor %}
      </div>

      <div class="field">
        <label for="first-name-id" class="label">Nombre(s):</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="first_name"
            id="first-name-id"
            {% if form.errors %}value="{{ form.first_name.value }}"{% endif %}
            required
          />
        </div>
      </div>

      <div class="field">
        <label for="last-name-id" class="label">Apellido(s):</label>
        <div class="control">
          <input
            class="input"
            type="text"
            name="last_name"
            id="last-name-id"
            {% if form.errors %}value="{{ form.last_name.value }}"{% endif %}
            required
          />
        </div>
      </div>

      <div class="field">
        <label for="password-id" class="label">Contraseña:</label>
        <div class="control">
          <input class="input" type="password" name="password" id="password-id" required />
        </div>
      </div>

      <div class="field">
        <label for="password-confirmation-id" class="label">
          Repetir contraseña:
        </label>
        <div class="control">
          <input
            class="input"
            type="password"
            name="password_confirmation"
            id="password-confirmation-id"
            required
          />
        </div>
      </div>

      <button class="button is-link" type="submit">Crear</button>
    </form>
  </div>
</section>
{% endblock content %}