sesion_07/locations/urls.py
"""Locations app URL config"""

from django.urls import path

from . import views


app_name = "locations"
urlpatterns = [
    path("create/", views.CreateAddressView.as_view(), name="create"),
    path("me/", views.ShowUserAddressView.as_view(), name="show"),
    path("delete/", views.DeleteAddressView.as_view(), name="delete"),
]

sesion_07/users/urls.py
"""Users app URL config"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

sesion_07/locations/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Address(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    street = models.CharField(max_length=255)
    number = models.CharField(max_length=255)
    zip_code = models.PositiveIntegerField()
    suburb = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    country = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self) -> str:
        return f"({self.latitude}, {self.longitude})"

sesion_07/locations/forms.py
"""Locations app forms"""

from django import forms

from .models import Address


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['user', ]

sesion_07/locations/views.py
"""Locations app views"""

from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import FormView, TemplateView, RedirectView

from .forms import AddressForm
from .models import Address


class CreateAddressView(LoginRequiredMixin, FormView):
    form_class = AddressForm
    template_name = "locations/create-address.html"
    success_url = reverse_lazy("locations:show")

    def form_valid(self, form):
        user = self.request.user
        queryset = Address.objects.filter(user=user)
        if queryset.exists():
            queryset.delete()

        address = form.save(commit=False)
        address.user = user
        address.save()
        return super().form_valid(form)


class ShowUserAddressView(LoginRequiredMixin, TemplateView):
    template_name = "locations/show-address.html"


class DeleteAddressView(LoginRequiredMixin, RedirectView):
    url = reverse_lazy("locations:show")

    def get_redirect_url(self, *args, **kwargs):
        address = get_object_or_404(Address, user=self.request.user)
        address.delete()
        return super().get_redirect_url(*args, **kwargs)

sesion_07/templates/locations/create-address.html
{% extends '_base.html' %}
{% load static %}

{% block meta %}
<script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkGw4ENpHr7pejus_3-NnuxU3TxspkDt0&libraries=places&callback=startAutocomplete">
</script>
<link rel="stylesheet" href="{% static 'css/map.css' %}">
{% endblock meta %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Crear dirección de usuario</h1>

    <div class="field">
      <label for="autocomplete-id" class="label">Ingrese dirección:</label>
      <div class="control">
        <input class="input" type="text" placeholder="Lomas de Chapultepec 33..." id="autocomplete-id">
      </div>
    </div>

    <div id="map"></div>

    <form method="post" id="hidden-form">
      {% csrf_token %}
      <input type="hidden" name="street" id="street-id" />
      <input type="hidden" name="number" id="number-id" />
      <input type="hidden" name="zip_code" id="zip-code-id" />
      <input type="hidden" name="suburb" id="suburb-id" />
      <input type="hidden" name="city" id="city-id" />
      <input type="hidden" name="state" id="state-id" />
      <input type="hidden" name="country" id="country-id" />
      <input type="hidden" name="latitude" id="latitude-id" />
      <input type="hidden" name="longitude" id="longitude-id" />
    </form>

    <button class="button is-link" id="submit-button" disabled>Crear dirección</button>
  </div>
</section>
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/createAddress.js' %}"></script>
{% endblock scripts %}

sesion_07/templates/locations/show-address.html
{% extends '_base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/map.css' %}">
{% endblock meta %}

{% block content %}
<section class="section">
  <div class="container">
    <h1 class="title">Mi dirección</h1>
    {% if not request.user.address %}
    <p class="is-danger">No has registrado una dirección</p>
    <a href="{% url 'locations:create' %}">Crear ahora</a>
    {% else %}
    <div id="map"></div>
    <a type="button" href="{% url 'locations:delete' %}" class="button is-danger is-light mt-3">Eliminar dirección</a>
    {% endif %}
  </div>
</section>
{% endblock content %}

{% block scripts %}
<script>
{% if request.user.address %}
  const address = {
    lat: {{ request.user.address.latitude }},
    lng: {{ request.user.address.longitude }},
  }
{% else %}
  const address = null
{% endif %}
</script>
<script src="{% static 'js/showAddress.js' %}"></script>
<script async
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDkGw4ENpHr7pejus_3-NnuxU3TxspkDt0&libraries=places&callback=createMap">
</script>
{% endblock scripts %}